[package]
name = "rshark"
version = "0.1.0"
authors = ["pmk21 <prithvikrishna49@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.10"
termion = "1.5"

[dependencies.pnet]
version = "0.26.0"
